typedef unsigned long uint64_t;

// A function decorated either with `UnmanagedCallersOnly` or `RuntimeExport` attributes in `Cosmos.Kernel`
extern void __Initialize_Kernel();             
// Generated by ilc at compile time when the parameter `--nativelib` is present.
extern void __managed__Startup();        
// Tentative name, this function would be exposed by the User's Main Project.
extern void __managed__Main();             

// Enable SSE support
void EnabledSSE() {
    uint64_t cr0, cr4;
    asm volatile ("mov %%cr0, %0" : "=r"(cr0));
    cr0 &= ~(1 << 2); // Clear EM (bit 2)
    cr0 |=  (1 << 1); // Set MP (bit 1)
    asm volatile ("mov %0, %%cr0" :: "r"(cr0));

    asm volatile ("mov %%cr4, %0" : "=r"(cr4));
    cr4 |= (3 << 9); // Set OSFXSR (bit 9) and OSXMMEXCPT (bit 10)
    asm volatile ("mov %0, %%cr4" :: "r"(cr4));
} 

// Entry point
void kmain()
{
    EnabledSSE();
    __Initialize_Kernel();
    __managed__Startup();
    __managed__Main();
}

