// A function decorated either with `UnmanagedCallersOnly` or `RuntimeExport` attributes in `Cosmos.Kernel`
extern void __Initialize_Kernel();             
// Generated by ilc at compile time when the parameter `--nativelib` is present.
extern void __managed__Startup();        
// Tentative name, this function would be exposed by the User's Main Project.
extern void __managed__Main();             

#ifdef __x86_64__
// Platform-specific initialization for x64 (enabling SSE)
extern void EnableSSE();
#endif

// Entry point
void kmain()
{
#ifdef __x86_64__
    EnableSSE();
#endif
    // ARM64: NEON is enabled by default, no initialization needed
    
    __Initialize_Kernel();
    __managed__Startup();
    __managed__Main();
}

