using System;

namespace Cosmos.Kernel.HAL.Devices.Graphic.SVGAII;

public enum SVGACOTableType : uint
{
    SVGA_COTABLE_MIN = 0,
    SVGA_COTABLE_RTVIEW = 0,
    SVGA_COTABLE_DSVIEW = 1,
    SVGA_COTABLE_SRVIEW = 2,
    SVGA_COTABLE_ELEMENTLAYOUT = 3,
    SVGA_COTABLE_BLENDSTATE = 4,
    SVGA_COTABLE_DEPTHSTENCIL = 5,
    SVGA_COTABLE_RASTERIZERSTATE = 6,
    SVGA_COTABLE_SAMPLER = 7,
    SVGA_COTABLE_STREAMOUTPUT = 8,
    SVGA_COTABLE_DXQUERY = 9,
    SVGA_COTABLE_DXSHADER = 10,
    SVGA_COTABLE_DX10_MAX = 11,
    SVGA_COTABLE_UAVIEW = 11,
    SVGA_COTABLE_MAX = 12,
}
