using System;

namespace Cosmos.Kernel.HAL.Devices.Graphic.SVGAII;

public enum FIFOCommand
{
    /// <summary>
    /// Update.
    /// </summary>
    Update = 1,
    /// <summary>
    /// Rectange fill.
    /// </summary>
    RECT_FILL = 2,
    /// <summary>
    /// Rectange copy.
    /// </summary>
    RECT_COPY = 3,
    /// <summary>
    /// Define bitmap.
    /// </summary>
    DEFINE_BITMAP = 4,
    /// <summary>
    /// Define bitmap scanline.
    /// </summary>
    DEFINE_BITMAP_SCANLINE = 5,
    /// <summary>
    /// Define pixmap.
    /// </summary>
    DEFINE_PIXMAP = 6,
    /// <summary>
    /// Define pixmap scanline.
    /// </summary>
    DEFINE_PIXMAP_SCANLINE = 7,
    /// <summary>
    /// Rectange bitmap fill.
    /// </summary>
    RECT_BITMAP_FILL = 8,
    /// <summary>
    /// Rectange pixmap fill.
    /// </summary>
    RECT_PIXMAP_FILL = 9,
    /// <summary>
    /// Rectange bitmap copy.
    /// </summary>
    RECT_BITMAP_COPY = 10,
    /// <summary>
    /// Rectange pixmap fill.
    /// </summary>
    RECT_PIXMAP_COPY = 11,
    /// <summary>
    /// Free object.
    /// </summary>
    FREE_OBJECT = 12,
    /// <summary>
    /// Rectangle raster operation fill.
    /// </summary>
    RECT_ROP_FILL = 13,
    /// <summary>
    /// Rectangle raster operation copy.
    /// </summary>
    RECT_ROP_COPY = 14,
    /// <summary>
    /// Rectangle raster operation bitmap fill.
    /// </summary>
    RECT_ROP_BITMAP_FILL = 15,
    /// <summary>
    /// Rectangle raster operation pixmap fill.
    /// </summary>
    RECT_ROP_PIXMAP_FILL = 16,
    /// <summary>
    /// Rectangle raster operation bitmap copy.
    /// </summary>
    RECT_ROP_BITMAP_COPY = 17,
    /// <summary>
    /// Rectangle raster operation pixmap copy.
    /// </summary>
    RECT_ROP_PIXMAP_COPY = 18,
    /// <summary>
    /// Define cursor.
    /// </summary>
    DEFINE_CURSOR = 19,
    /// <summary>
    /// Display cursor.
    /// </summary>
    DISPLAY_CURSOR = 20,
    /// <summary>
    /// Move cursor.
    /// </summary>
    MOVE_CURSOR = 21,
    /// <summary>
    /// Define alpha cursor.
    /// </summary>
    DEFINE_ALPHA_CURSOR = 22,

    DEFINE_SURFACE = 1040,
    SURFACE_COPY = 1040 + 2,
    SETMATERIAL = 1040 + 12,
    SETLIGHTDATA = 1040 + 13,
    SETLIGHTENABLE = 1040 + 14,
    SETVIEWPORT = 1040 + 15,
    SETZRANGE = 1040 + 8,

    DEFINE_CONTEXT = 1040 + 5,
    DESTROY_CONTEXT = 1040 + 6,
    DEFINE_SURFACE_V2 = 1040 + 30,  // Use V2 surface definition
    DESTROY_SURFACE = 1040 + 1,
    DESTROY_SHADER = 1040 + 20,
    SET_RENDER_TARGET = 1040 + 10,
    CLEAR = 1040 + 17,
    SET_VIEWPORT = 1040 + 15,
    SET_ZRANGE = 1040 + 8,
    PRESENT = 1040 + 18,
    SETRENDERSTATE = 1040 + 9,
    SURFACE_DMA = 1040 + 4,
    DRAW_PRIMITIVES = 1040 + 23,
    SETTRANSFORM = 1040 + 7,
    SETTEXTURESTATE = 1040 + 11,
    SHADER_DEFINE = 1040 + 19,
    SET_SHADER = 1040 + 21,
    SET_SHADER_CONST = 1040 + 22,

    // SVGAII 2.3 commands
    SVGA_3D_CMD_DEFINE_GB_MOB = 1093,
	SVGA_3D_CMD_DESTROY_GB_MOB = 1094,
	SVGA_3D_CMD_DEAD3 = 1095,
	SVGA_3D_CMD_UPDATE_GB_MOB_MAPPING = 1096,

	SVGA_3D_CMD_DEFINE_GB_SURFACE = 1097,
	SVGA_3D_CMD_DESTROY_GB_SURFACE = 1098,
	SVGA_3D_CMD_BIND_GB_SURFACE = 1099,
	SVGA_3D_CMD_COND_BIND_GB_SURFACE = 1100,
	SVGA_3D_CMD_UPDATE_GB_IMAGE = 1101,
	SVGA_3D_CMD_UPDATE_GB_SURFACE = 1102,
	SVGA_3D_CMD_READBACK_GB_IMAGE = 1103,
	SVGA_3D_CMD_READBACK_GB_SURFACE = 1104,
	SVGA_3D_CMD_INVALIDATE_GB_IMAGE = 1105,
	SVGA_3D_CMD_INVALIDATE_GB_SURFACE = 1106,

	SVGA_3D_CMD_DEFINE_GB_CONTEXT = 1107,
	SVGA_3D_CMD_DESTROY_GB_CONTEXT = 1108,
	SVGA_3D_CMD_BIND_GB_CONTEXT = 1109,
	SVGA_3D_CMD_READBACK_GB_CONTEXT = 1110,
	SVGA_3D_CMD_INVALIDATE_GB_CONTEXT = 1111,

	SVGA_3D_CMD_DEFINE_GB_SHADER = 1112,
	SVGA_3D_CMD_DESTROY_GB_SHADER = 1113,
	SVGA_3D_CMD_BIND_GB_SHADER = 1114,

	SVGA_3D_CMD_SET_OTABLE_BASE64 = 1115,

	SVGA_3D_CMD_BEGIN_GB_QUERY = 1116,
	SVGA_3D_CMD_END_GB_QUERY = 1117,
	SVGA_3D_CMD_WAIT_FOR_GB_QUERY = 1118,
    SVGA_3D_CMD_DEFINE_GB_SCREENTARGET = 1124,
	SVGA_3D_CMD_DESTROY_GB_SCREENTARGET = 1125,
	SVGA_3D_CMD_BIND_GB_SCREENTARGET = 1126,
	SVGA_3D_CMD_UPDATE_GB_SCREENTARGET = 1127,

	SVGA_3D_CMD_READBACK_GB_IMAGE_PARTIAL = 1128,
	SVGA_3D_CMD_INVALIDATE_GB_IMAGE_PARTIAL = 1129,

	SVGA_3D_CMD_SET_GB_SHADERCONSTS_INLINE = 1130,

	SVGA_3D_CMD_GB_SCREEN_DMA = 1131,
	SVGA_3D_CMD_BIND_GB_SURFACE_WITH_PITCH = 1132,
	SVGA_3D_CMD_GB_MOB_FENCE = 1133,
	SVGA_3D_CMD_DEFINE_GB_SURFACE_V2 = 1134,
	SVGA_3D_CMD_DEFINE_GB_MOB64 = 1135,
	SVGA_3D_CMD_REDEFINE_GB_MOB64 = 1136,
    SVGA_3D_CMD_UPDATE_GB_SCREENTARGET_V2 = 1266,

	SVGA_3D_CMD_DEFINE_GB_SURFACE_V4 = 1267,

    SVGA_3D_CMD_DX_MIN = 1143,
    SVGA_3D_CMD_DX_DEFINE_CONTEXT = 1143,
    SVGA_3D_CMD_DX_DESTROY_CONTEXT = 1144,
    SVGA_3D_CMD_DX_BIND_CONTEXT = 1145,
    SVGA_3D_CMD_DX_READBACK_CONTEXT = 1146,
    SVGA_3D_CMD_DX_INVALIDATE_CONTEXT = 1147,
    SVGA_3D_CMD_DX_SET_SINGLE_CONSTANT_BUFFER = 1148,
    SVGA_3D_CMD_DX_SET_SHADER_RESOURCES = 1149,
    SVGA_3D_CMD_DX_SET_SHADER = 1150,
    SVGA_3D_CMD_DX_SET_SAMPLERS = 1151,
    SVGA_3D_CMD_DX_DRAW = 1152,
    SVGA_3D_CMD_DX_DRAW_INDEXED = 1153,
    SVGA_3D_CMD_DX_DRAW_INSTANCED = 1154,
    SVGA_3D_CMD_DX_DRAW_INDEXED_INSTANCED = 1155,
    SVGA_3D_CMD_DX_DRAW_AUTO = 1156,
    SVGA_3D_CMD_DX_SET_INPUT_LAYOUT = 1157,
    SVGA_3D_CMD_DX_SET_VERTEX_BUFFERS = 1158,
    SVGA_3D_CMD_DX_SET_INDEX_BUFFER = 1159,
    SVGA_3D_CMD_DX_SET_TOPOLOGY = 1160,
    SVGA_3D_CMD_DX_SET_RENDERTARGETS = 1161,
    SVGA_3D_CMD_DX_SET_BLEND_STATE = 1162,
    SVGA_3D_CMD_DX_SET_DEPTHSTENCIL_STATE = 1163,
    SVGA_3D_CMD_DX_SET_RASTERIZER_STATE = 1164,
    SVGA_3D_CMD_DX_DEFINE_QUERY = 1165,
    SVGA_3D_CMD_DX_DESTROY_QUERY = 1166,
    SVGA_3D_CMD_DX_BIND_QUERY = 1167,
    SVGA_3D_CMD_DX_SET_QUERY_OFFSET = 1168,
    SVGA_3D_CMD_DX_BEGIN_QUERY = 1169,
    SVGA_3D_CMD_DX_END_QUERY = 1170,
    SVGA_3D_CMD_DX_READBACK_QUERY = 1171,
    SVGA_3D_CMD_DX_SET_PREDICATION = 1172,
    SVGA_3D_CMD_DX_SET_SOTARGETS = 1173,
    SVGA_3D_CMD_DX_SET_VIEWPORTS = 1174,
    SVGA_3D_CMD_DX_SET_SCISSORRECTS = 1175,
    SVGA_3D_CMD_DX_CLEAR_RENDERTARGET_VIEW = 1176,
    SVGA_3D_CMD_DX_CLEAR_DEPTHSTENCIL_VIEW = 1177,
    SVGA_3D_CMD_DX_PRED_COPY_REGION = 1178,
    SVGA_3D_CMD_DX_PRED_COPY = 1179,
    SVGA_3D_CMD_DX_PRESENTBLT = 1180,
    SVGA_3D_CMD_DX_GENMIPS = 1181,
    SVGA_3D_CMD_DX_UPDATE_SUBRESOURCE = 1182,
    SVGA_3D_CMD_DX_READBACK_SUBRESOURCE = 1183,
    SVGA_3D_CMD_DX_INVALIDATE_SUBRESOURCE = 1184,
    SVGA_3D_CMD_DX_DEFINE_SHADERRESOURCE_VIEW = 1185,
    SVGA_3D_CMD_DX_DESTROY_SHADERRESOURCE_VIEW = 1186,
    SVGA_3D_CMD_DX_DEFINE_RENDERTARGET_VIEW = 1187,
    SVGA_3D_CMD_DX_DESTROY_RENDERTARGET_VIEW = 1188,
    SVGA_3D_CMD_NOP_ERROR = 1137,

    SVGA_3D_CMD_SET_VERTEX_STREAMS = 1138,
    SVGA_3D_CMD_SET_VERTEX_DECLS = 1139,
    SVGA_3D_CMD_SET_VERTEX_DIVISORS = 1140,
    SVGA_3D_CMD_DRAW = 1141,
    SVGA_3D_CMD_DRAW_INDEXED = 1142,

    SVGA_3D_CMD_DX_DEFINE_DEPTHSTENCIL_VIEW = 1189,
    SVGA_3D_CMD_DX_DESTROY_DEPTHSTENCIL_VIEW = 1190,
    SVGA_3D_CMD_DX_DEFINE_ELEMENTLAYOUT = 1191,
    SVGA_3D_CMD_DX_DESTROY_ELEMENTLAYOUT = 1192,
    SVGA_3D_CMD_DX_DEFINE_BLEND_STATE = 1193,
    SVGA_3D_CMD_DX_DESTROY_BLEND_STATE = 1194,
    SVGA_3D_CMD_DX_DEFINE_DEPTHSTENCIL_STATE = 1195,
    SVGA_3D_CMD_DX_DESTROY_DEPTHSTENCIL_STATE = 1196,
    SVGA_3D_CMD_DX_DEFINE_RASTERIZER_STATE = 1197,
    SVGA_3D_CMD_DX_DESTROY_RASTERIZER_STATE = 1198,
    SVGA_3D_CMD_DX_DEFINE_SAMPLER_STATE = 1199,
    SVGA_3D_CMD_DX_DESTROY_SAMPLER_STATE = 1200,
    SVGA_3D_CMD_DX_DEFINE_SHADER = 1201,
    SVGA_3D_CMD_DX_DESTROY_SHADER = 1202,
    SVGA_3D_CMD_DX_BIND_SHADER = 1203,
    SVGA_3D_CMD_DX_DEFINE_STREAMOUTPUT = 1204,
    SVGA_3D_CMD_DX_DESTROY_STREAMOUTPUT = 1205,
    SVGA_3D_CMD_DX_SET_STREAMOUTPUT = 1206,
    SVGA_3D_CMD_DX_SET_COTABLE = 1207,
    SVGA_3D_CMD_DX_READBACK_COTABLE = 1208,
    SVGA_3D_CMD_DX_BUFFER_COPY = 1209,
    SVGA_3D_CMD_DX_TRANSFER_FROM_BUFFER = 1210,
    SVGA_3D_CMD_DX_SURFACE_COPY_AND_READBACK = 1211,
    SVGA_3D_CMD_DX_MOVE_QUERY = 1212,
    SVGA_3D_CMD_DX_BIND_ALL_QUERY = 1213,
    SVGA_3D_CMD_DX_READBACK_ALL_QUERY = 1214,
    SVGA_3D_CMD_DX_PRED_TRANSFER_FROM_BUFFER = 1215,
    SVGA_3D_CMD_DX_MOB_FENCE_64 = 1216,
    SVGA_3D_CMD_DX_BIND_ALL_SHADER = 1217,
    SVGA_3D_CMD_DX_HINT = 1218,
    SVGA_3D_CMD_DX_BUFFER_UPDATE = 1219,
    SVGA_3D_CMD_DX_SET_VS_CONSTANT_BUFFER_OFFSET = 1220,
    SVGA_3D_CMD_DX_SET_PS_CONSTANT_BUFFER_OFFSET = 1221,
    SVGA_3D_CMD_DX_SET_GS_CONSTANT_BUFFER_OFFSET = 1222,
    SVGA_3D_CMD_DX_SET_HS_CONSTANT_BUFFER_OFFSET = 1223,
    SVGA_3D_CMD_DX_SET_DS_CONSTANT_BUFFER_OFFSET = 1224,
    SVGA_3D_CMD_DX_SET_CS_CONSTANT_BUFFER_OFFSET = 1225,

    SVGA_3D_CMD_DX_COND_BIND_ALL_SHADER = 1226,
    SVGA_3D_CMD_DX_MAX = 1227,

    SVGA_3D_CMD_DX_TRANSFER_TO_BUFFER = 1257,
    SVGA_3D_CMD_DX_SET_STRUCTURE_COUNT = 1258,

    SVGA_3D_CMD_DX_PRED_STAGING_COPY = 1281,
    SVGA_3D_CMD_DX_STAGING_COPY = 1282,
    SVGA_3D_CMD_DX_PRED_STAGING_COPY_REGION = 1283,
    SVGA_3D_CMD_DX_SET_VERTEX_BUFFERS_V2 = 1284,
    SVGA_3D_CMD_DX_SET_INDEX_BUFFER_V2 = 1285,
    SVGA_3D_CMD_DX_SET_VERTEX_BUFFERS_OFFSET_AND_SIZE = 1286,
    SVGA_3D_CMD_DX_SET_INDEX_BUFFER_OFFSET_AND_SIZE = 1287,
    SVGA_3D_CMD_DX_DEFINE_RASTERIZER_STATE_V2 = 1288,
    SVGA_3D_CMD_DX_PRED_STAGING_CONVERT_REGION = 1289,
    SVGA_3D_CMD_DX_PRED_STAGING_CONVERT = 1290,
    SVGA_3D_CMD_DX_STAGING_BUFFER_COPY = 1291,

    SVGA_3D_CMD_DX_BIND_SHADER_IFACE = 1277,
    SVGA_3D_CMD_DX_DEFINE_DEPTHSTENCIL_VIEW_V2 = 1272,
    SVGA_3D_CMD_DX_DEFINE_STREAMOUTPUT_WITH_MOB = 1273,
    SVGA_3D_CMD_DX_SET_SHADER_IFACE = 1274,
    SVGA_3D_CMD_DX_BIND_STREAMOUTPUT = 1275,

    SVGA_3D_CMD_DX_SET_CS_UA_VIEWS = 1268,
    SVGA_3D_CMD_DX_SET_MIN_LOD = 1269,
    SVGA_3D_CMD_DX_COPY_COTABLE_INTO_MOB = 1265,

    SVGA_3D_CMD_DX_DRAW_INDEXED_INSTANCED_INDIRECT = 1251,
    SVGA_3D_CMD_DX_DRAW_INSTANCED_INDIRECT = 1252,
    SVGA_3D_CMD_DX_DISPATCH = 1253,
    SVGA_3D_CMD_DX_DISPATCH_INDIRECT = 1254,

    SVGA_3D_CMD_DX_DEFINE_UA_VIEW = 1245,
    SVGA_3D_CMD_DX_DESTROY_UA_VIEW = 1246,
    SVGA_3D_CMD_DX_CLEAR_UA_VIEW_UINT = 1247,
    SVGA_3D_CMD_DX_CLEAR_UA_VIEW_FLOAT = 1248,
    SVGA_3D_CMD_DX_COPY_STRUCTURE_COUNT = 1249,
    SVGA_3D_CMD_DX_SET_UA_VIEWS = 1250,

    SVGA_3D_CMD_DX_RESOLVE_COPY = 1240,
    SVGA_3D_CMD_DX_PRED_RESOLVE_COPY = 1241,
    SVGA_3D_CMD_DX_PRED_CONVERT_REGION = 1242,
    SVGA_3D_CMD_DX_PRED_CONVERT = 1243,

    SVGA_3D_CMD_DX_GROW_COTABLE = 1237,
}
