namespace Cosmos.Kernel.HAL.Devices.Graphic.SVGAII;

public enum OTableType : uint
{
    SVGA_OTABLE_MOB = 0,
	SVGA_OTABLE_MIN = 0,
	SVGA_OTABLE_SURFACE = 1,
	SVGA_OTABLE_CONTEXT = 2,
	SVGA_OTABLE_SHADER = 3,
	SVGA_OTABLE_SCREENTARGET = 4,

	SVGA_OTABLE_DX9_MAX = 5,

	SVGA_OTABLE_DXCONTEXT = 5,
	SVGA_OTABLE_DX_MAX = 6,

	SVGA_OTABLE_DEVEL_MAX = 6,
	SVGA_OTABLE_MAX = 6,

	SVGA_OTABLE_RESERVED1 = 6,
	SVGA_OTABLE_RESERVED2 = 7,
	SVGA_OTABLE_BUG_1952836_MAX = 8,
}
