using System;

namespace Cosmos.Kernel.HAL.Devices.Graphic.SVGAII;

public enum TextureFilter
{
    SVGA3D_TEX_FILTER_NONE = 0,
	SVGA3D_TEX_FILTER_MIN = 0,
	SVGA3D_TEX_FILTER_NEAREST = 1,
	SVGA3D_TEX_FILTER_LINEAR = 2,
	SVGA3D_TEX_FILTER_ANISOTROPIC = 3,
	SVGA3D_TEX_FILTER_FLATCUBIC = 4,
	SVGA3D_TEX_FILTER_GAUSSIANCUBIC = 5,
	SVGA3D_TEX_FILTER_PYRAMIDALQUAD = 6,
	SVGA3D_TEX_FILTER_GAUSSIANQUAD = 7,
	SVGA3D_TEX_FILTER_MAX
}
