using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Cosmos.Kernel.SourceGenerators;

[Generator]
public class LoggerGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Cosmos.Kernel.Core.Logging.LoggerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            predicate: static (node, _) => node is ClassDeclarationSyntax cds
                && cds.Modifiers.Any(m => m.Text == "partial"),
            transform: static (ctx, _) => ctx);

        context.RegisterSourceOutput(classes, (spc, ctx) =>
        {
            INamedTypeSymbol symbol = (INamedTypeSymbol)ctx.TargetSymbol;
            string? ns = symbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : symbol.ContainingNamespace.ToDisplayString();
            string className = symbol.Name;

            string category = className;
            foreach (AttributeData attr in symbol.GetAttributes())
            {
                if (attr.AttributeClass?.ToDisplayString() != AttributeFullName)
                {
                    continue;
                }

                foreach (System.Collections.Generic.KeyValuePair<string, TypedConstant> named in attr.NamedArguments)
                {
                    if (named.Key == "Category" && named.Value.Value is string s && !string.IsNullOrEmpty(s))
                    {
                        category = s;
                    }
                }
            }

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Diagnostics;");
            sb.AppendLine("using Cosmos.Kernel.Core.Logging;");
            sb.AppendLine();
            if (ns != null)
            {
                sb.Append("namespace ").Append(ns).AppendLine(";");
                sb.AppendLine();
            }
            sb.Append("partial class ").AppendLine(className);
            sb.AppendLine("{");
            sb.AppendLine("    private static class Log");
            sb.AppendLine("    {");
            sb.Append("        private const string Category = \"").Append(category).AppendLine("\";");
            sb.AppendLine("        public static void Info(string message)     => LogBackend.Write(Category, LogLevel.Information, message);");
            sb.AppendLine("        public static void Warning(string message)  => LogBackend.Write(Category, LogLevel.Warning, message);");
            sb.AppendLine("        public static void Error(string message)    => LogBackend.Write(Category, LogLevel.Error, message);");
            sb.AppendLine("        public static void Critical(string message) => LogBackend.Write(Category, LogLevel.Critical, message);");
            sb.AppendLine("        [Conditional(\"COSMOSDEBUG\")]");
            sb.AppendLine("        public static void Debug(string message)    => LogBackend.Write(Category, LogLevel.Debug, message);");
            sb.AppendLine("        [Conditional(\"COSMOSDEBUG\")]");
            sb.AppendLine("        public static void Trace(string message)    => LogBackend.Write(Category, LogLevel.Trace, message);");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            string hintName = ns == null
                ? $"{className}.Logger.g.cs"
                : $"{ns}.{className}.Logger.g.cs";
            spc.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }
}
