// This code is licensed under MIT license (see LICENSE for details)

using System.Diagnostics;

namespace Cosmos.Kernel.Core.IO;

/// <summary>
/// Allocation-free primitive trace output for pre-GC-init code (PageAllocator, SmallHeap,
/// GarbageCollector, ManagedModule). Writes numbers and hex addresses directly to UART
/// without constructing heap strings — safe before the GC is initialized.
///
/// Every method is marked <see cref="ConditionalAttribute"/> with <c>COSMOSDEBUG</c>:
/// call sites and all argument expressions are removed entirely by the compiler when the
/// symbol is undefined. No allocation, no work in release builds.
///
/// Use <c>Log.*</c> (generated by <c>[Logger]</c>) for all post-GC-init code.
/// Use <c>Serial.*</c> for fatal/halt paths that must always reach the UART regardless
/// of log level or GC state.
/// </summary>
public static class SerialDebug
{
    [Conditional("COSMOSDEBUG")]
    public static void WriteString(string str) => Serial.WriteString(str);

    [Conditional("COSMOSDEBUG")]
    public static void WriteNumber(ulong number, bool hex = false) => Serial.WriteNumber(number, hex);

    [Conditional("COSMOSDEBUG")]
    public static void WriteNumber(uint number, bool hex = false) => Serial.WriteNumber(number, hex);

    [Conditional("COSMOSDEBUG")]
    public static void WriteNumber(int number, bool hex = false) => Serial.WriteNumber(number, hex);

    [Conditional("COSMOSDEBUG")]
    public static void WriteNumber(long number, bool hex = false) => Serial.WriteNumber(number, hex);

    [Conditional("COSMOSDEBUG")]
    public static void WriteHex(ulong number) => Serial.WriteHex(number);

    [Conditional("COSMOSDEBUG")]
    public static void WriteHex(uint number) => Serial.WriteHex(number);

    [Conditional("COSMOSDEBUG")]
    public static void WriteHexWithPrefix(ulong number) => Serial.WriteHexWithPrefix(number);

    [Conditional("COSMOSDEBUG")]
    public static void WriteHexWithPrefix(uint number) => Serial.WriteHexWithPrefix(number);

    [Conditional("COSMOSDEBUG")]
    public static void Write(params object?[] args) => Serial.Write(args);
}
